image: 10.0.0.232:5000/ubuntu-loaded

stages:
  - verify
  - deploy
  - graduate

build-job:
  stage: verify
  tags:
    - ubuntu-loaded
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh init-all.sh
    - sh build-all.sh

test-software-job:
  stage: verify
  tags:
    - ubuntu-loaded
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh init-all.sh
    - sh build-tests.sh
    - sh test-software.sh

deploy-update-staging:
  stage: deploy
  tags:
    - ubuntu-loaded
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh deploy-dev-update.sh

deploy-staging:
  stage: deploy
  tags:
    - ubuntu-loaded
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh deploy-dev.sh

graduate-job:
  stage: graduate
  tags:
    - ubuntu-loaded
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh clean.sh
    - sh graduate.sh

