stages:
  - checkout
  - init
  - build

checkout-job:
  stage: checkout
  script:
    - git checkout "$CI_COMMIT_BRANCH"

init-job:
  stage: init
  script:
    - sh init-all.sh

build-job:
  stage: build
  script:
    - sh build.sh
