image: 10.0.0.101:5000/ubuntu-loaded

stages:
  - build
  - verify
  - release
  - update
  - install
  - graduate
  
variables:
     GIT_SUBMODULE_STRATEGY: recursive

build-sketches:
  stage: build
  tags:
    - docker
  before_script:
    - git config --global user.email "admin@makerzone.com.au"
    - git config --global user.name "John Rebbeck"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
    - cat full-version.txt
  script:
    - sh init-sketches.sh
    - echo "..." #sh build-sketches.sh
    
build:
  stage: build
  tags:
    - docker
  before_script:
    - git config --global user.email "admin@makerzone.com.au"
    - git config --global user.name "John Rebbeck"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull -f
    - cat full-version.txt
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - sh init.sh
    - sh init-apps.sh
    - sh init-tests.sh
    - sh build-cli.sh
    - sh build-tests.sh
  artifacts:
    paths:
      - lib/**
      - bin/Release/**
      - scripts/apps/**

build-www:
  stage: build
  tags:
    - docker
  before_script:
    - git config --global user.email "admin@makerzone.com.au"
    - git config --global user.name "John Rebbeck"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
    - git submodule update --init
    - cat full-version.txt
  script:
    - sh init-www.sh
    - sh build-www.sh
  artifacts:
    paths:
      - www/SystemManagerWWW/src/GrowSense.SystemManager.WWW/bin/**

test-cli-slow:
  stage: verify
  tags:
    - docker
  before_script:
    - git config --global user.email "admin@makerzone.com.au"
    - git config --global user.name "John Rebbeck"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
  script:
    - sh test.sh Slow
  dependencies:
    - build
    
test-cli-fast:
  stage: verify
  tags:
    - docker
  before_script:
    - git config --global user.email "admin@makerzone.com.au"
    - git config --global user.name "John Rebbeck"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
  script:
    - sh test.sh Fast
  dependencies:
    - build
    
test-unit:
  stage: verify
  tags:
    - docker
  before_script:
    - git config --global user.email "admin@makerzone.com.au"
    - git config --global user.name "John Rebbeck"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
  script:
    - sh test.sh Unit
  dependencies:
    - build
    
test-deploy:
  stage: verify
  tags:
    - docker
  before_script:
    - git config --global user.email "admin@makerzone.com.au"
    - git config --global user.name "John Rebbeck"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull -f
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - cat full-version.txt
  script:
    - sh test.sh DeployInstall
  dependencies:
    - build
    
release:
  stage: release
  tags:
    - docker
  script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
    - bash create-release-zip.sh
    - bash publish-github-release.sh
  dependencies:
    - build
    - build-www

deploy-update-staging:
  stage: update
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - echo "Skipping update" # sh deploy-dev-update.sh


graduate:
  stage: graduate
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh clean.sh
    - sh graduate.
  dependencies:
    - build




