image: 10.0.0.101:5000/ubuntu-loaded

stages:
  - build
  - verify
  - update
  - install
  - graduate


build-sketches:
  stage: build
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh init-sketches.sh
    - sh build-sketches.sh
    
build:
  stage: build
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh init.sh
    - sh build.sh
    - sh build-tests.sh
  artifacts:
    paths:
      - lib/**
      - bin/Release/**

test-software-slow:
  stage: verify
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh test.sh slow
  dependencies:
    - build
    
test-software-fast:
  stage: verify
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh test.sh fast
  dependencies:
    - build
    
test-software-unit:
  stage: verify
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh test.sh fast
  dependencies:
    - build

deploy-update-staging:
  stage: update
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh deploy-dev-update.sh

deploy-staging:
  stage: install
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh deploy-dev.sh

graduate:
  stage: graduate
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh clean.sh
    - sh graduate.
  dependencies:
    - build


