image: 10.0.0.232:5000/ubuntu-loaded


stages:
  - build

build-job:
  stage: build
  tags:
    - ubuntu-loaded
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh init-all.sh
    - sh build.sh
