image: 10.0.0.232:5000/ubuntu-loaded

stages:
  - verify
  - update
  - install
  - graduate

build:
  stage: verify
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh init-all.sh
    - sh build-all.sh

test-software:
  stage: verify
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh init-all.sh
    - sh build-tests.sh
    - sh test-software.sh

deploy-update-staging:
  stage: update
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh deploy-dev-update.sh

deploy-staging:
  stage: install
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh deploy-dev.sh

graduate:
  stage: graduate
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh clean.sh
    - sh graduate.
  dependencies:
    - build-job


