image: ubuntu-loaded


stages:
  - checkout
  - init
  - build

checkout-job:
  stage: checkout
  tags:
    - ubuntu-loaded
  script:
    - git checkout "$CI_COMMIT_BRANCH"

init-job:
  stage: init
  tags:
    - ubuntu-loaded
  script:
    - sh init-all.sh

build-job:
  stage: build
  tags:
    - ubuntu-loaded
  script:
    - sh build.sh
