image: local:5000/ubuntu-loaded

stages:
  - build
  - verify
  - release
  - update
  - install
  - graduate
  - version
  
variables:
     GIT_SUBMODULE_STRATEGY: recursive

build-sketches:
  stage: build
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
    - cp .gitmodules.lan .gitmodules
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - cat full-version.txt
  script:
    - sh init-sketches.sh
    - echo "..." #sh build-sketches.sh
    
build:
  stage: build
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
    - cp .gitmodules.lan .gitmodules
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - cat full-version.txt
  script:
    - sh init.sh
    - sh init-apps.sh
    - sh init-tests.sh
    - sh init-cli.sh
    - sh build-cli.sh
    - sh build-tests.sh
  artifacts:
    paths:
      - lib/**
      - bin/Release/**
      - scripts/apps/**

build-www:
  stage: build
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
    - git submodule update --init
    - cat full-version.txt
  script:
    - sh init-www.sh
    - sh build-www.sh
  artifacts:
    paths:
      - www/SystemManagerWWW/src/GrowSense.SystemManager.WWW/bin/**

test-cli-slow:
  stage: verify
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
    - cat full-version.txt
  script:
    - sh test.sh Slow
  dependencies:
    - build
    
test-cli-fast:
  stage: verify
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
    - cat full-version.txt
  script:
    - echo "Skipped" # echo "PWD $PWD"
    - echo "Skipped" # ls
    - echo "Skipped" # sh test.sh Fast
  dependencies:
    - build
    
test-unit:
  stage: verify
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
    - cat full-version.txt
  script:
    - sh test.sh Unit
  dependencies:
    - build
    
test-deploy:
  stage: verify
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - cp .gitmodules.lan .gitmodules
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - cat full-version.txt
  script:
    - bash test.sh DeployDirectUpgrade
    - bash test.sh DeployDirectInstall
    - echo "Skipping check deployment" #bash check-deployment.sh
  dependencies:
    - build
    
release:
  stage: release
  tags:
    - docker
  script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
    - bash increment-version.sh
    - bash delete-github-release.sh
    - bash create-release-zip.sh
    - bash publish-github-release.sh
  dependencies:
    - build
    - build-www

graduate:
  stage: graduate
  tags:
    - docker
  before_script:
    - git remote set-url origin https://$GHTOKEN@github.com/GrowSense/Index.git
    - git remote add lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/index.git || git remote set-url lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/index.git
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
  script:
    - bash clean.sh
    - bash graduate.sh
  dependencies:
    - build

version:
  stage: version
  tags:
    - docker
  before_script:
    - git remote set-url origin https://$GHTOKEN@github.com/GrowSense/Index.git
    - git remote add lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/index.git || git remote set-url lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/index.git
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH" && git pull --force && git merge -Xtheirs $CI_COMMIT_BRANCH
    - bash pull.sh
  script:
    - bash increment-version.sh
    - bash push-version.sh
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
