image: 10.0.0.232:5000/ubuntu-loaded

stages:
  - verify
  - deploy

build-job:
  stage: verify
  tags:
    - ubuntu-loaded
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh init-all.sh
    - sh build-all.sh

test-software-job:
  stage: verify
  tags:
    - ubuntu-loaded
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh init-all.sh
    - sh build-tests.sh
    - sh test-software.sh

deploy-job:
  stage: deploy
  tags:
    - ubuntu-loaded
  script:
    - sh deploy-dev-update.sh
    - sh deploy-master-update.sh
    - sh sh deploy-rc-update.sh